import { Flex, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import "../theme-config.css";
import VerticalNavbar from "./VerticalNavbar";
import HorizontalNavBar from "./HorizontalNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Caladea:ital,wght@0,400;0,700;1,400;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <Theme accentColor="blue">
          <Toaster />
          <main className={`h-screen bg-slate-100`}>
            <Flex className="w-full h-full p-2" gap={"2"}>
              <Flex className="w-1/5 bg-white border rounded-lg overflow-hidden">
                <VerticalNavbar />
              </Flex>
              <Flex className="w-4/5" direction={"column"} gap={"2"}>
                <Flex className="bg-white border rounded-lg overflow-hidden">
                  <HorizontalNavBar />
                </Flex>
                <Flex className="h-full w-full rounded-lg border overflow-hidden shadow-lg bg-white">
                  {children}
                </Flex>
              </Flex>
            </Flex>
          </main>
        </Theme>
      </body>
    </html>
  );
}
